### ISSUE TITLE
Bitcoin Diamond

### ISSUE THREAD

**Issue by odracir07** [someone235/btc-forks-balance#10]
Hello, 

Can you add Bitcoin Diamond to the balance?

**Comment by someone235** [comment]
Sorry, I can't add Bitcoin Diamond, because its block explorer is buggy and I can't fetch addresses' balance: http://explorer.btcd.io/#/address?loading=true&address=1PPgkYu1owxYuY3TsEDEu3vke44UpdKhmZ
