### ISSUE TITLE
Add UBTC

### ISSUE THREAD

**Issue by a-maly** [someone235/btc-forks-balance#11]
https://coinmarketcap.com/currencies/united-bitcoin/
https://www.ub.com/explorer/address?address=

**Comment by someone235** [comment]
Doesn't work for me: https://www.ub.com/explorer/address?address=1F5n1fKsNU5JZGNnHyJRnbz1azRyHnut9S

**Comment by a-maly** [comment]
Check other adress. There no UBTC (fork was earlier 2017.12.12)

**Comment by someone235** [comment]
You're right. I added it now
