### ISSUE TITLE
not functioning 

### ISSUE THREAD

**Issue by odracir07** [someone235/btc-forks-balance#4]
hi, i tried checking my wallet address but nothing seems to happen after i hit the check button. also can you add b2x to the list?

**Comment by someone235** [comment]
Hi,
The sure works for me, but I'm aware of some issues when using Edge browser, so if you're using it, you can try to use another browser until I'll have time to investigate these issues.
If this is not the case pls share more details about your case. For example, which browser do you use? Which version? What address have you checked?

**Comment by someone235** [comment]
About b2x: I'm adding only forks with live mainnet, a block explorer and that are listed in coinmarketcap. When this will be the case, of course I will add it.
