### ISSUE TITLE
Request to add Super Bitcoin (SBTC) and Bitcoin Diamond (BCD)

### ISSUE THREAD

**Issue by mgondzik** [someone235/btc-forks-balance#5]
Hi,
Please add SBTC and BCD to https://someone235.github.io/btc-forks-balance/ 
thanks in advance!
regards
Mike

**Comment by someone235** [comment]
I'm adding only forks with live mainnet, a block explorer and that are listed in coinmarketcap. When this will be the case, of course I will add them.

**Comment by mgondzik** [comment]
Hi again,
Plesae take a look here: https://btcdiv.com/# 
It looks like some new forks have gone live already :)
/M.

**Comment by someone235** [comment]
I added SBTC yesterday. Besides that, do you know if any other fork has working block explorer?

**Comment by mgondzik** [comment]
probably these?
https://github.com/SegwitB2X/bitcoin2x/releases  
http://explorer.btcd.io/#/

**Comment by someone235** [comment]
B2X indeed has a working block explorer, so I will add it in the evening.
About btcd, its explorer is buggy, and doesn't have the option to show address balance (e.g http://explorer.btcd.io/#/address?loading=true&address=1PPgkYu1owxYuY3TsEDEu3vke44UpdKhmZ )

**Comment by mgondzik** [comment]
yes, indeed, I got the same impression 
- thanks! :)

**Comment by someone235** [comment]
added

**Comment by mgondzik** [comment]
Hi,
Actually I saw it yesterday, but today B2X doesn't appear..?

**Comment by someone235** [comment]
Is it the same device? Otherwise it might be cache problem

**Comment by mgondzik** [comment]
could be! tested it in incognito mode  and it works for all forks, B2X included :)
